#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ActionBar.Resource", IsApplication=true)]

namespace ActionBar
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::ActionBar.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::ActionBar.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::ActionBar.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040004
			public const int margin_huge = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int margin_large = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int margin_medium = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int margin_small = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int margin_tiny = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int page_margin = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int standard_touch_target_size = 2130968581;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int drawer_shadow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_account_options = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_action_call = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_email = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_facebook = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_twitter = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_drawer = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070008
			public const int activity_list = 2131165192;
			
			// aapt resource value: 0x7f070016
			public const int amount = 2131165206;
			
			// aapt resource value: 0x7f070005
			public const int amountTxt = 2131165189;
			
			// aapt resource value: 0x7f070024
			public const int bic = 2131165220;
			
			// aapt resource value: 0x7f07000f
			public const int button1 = 2131165199;
			
			// aapt resource value: 0x7f070028
			public const int button2 = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int contentFrame = 2131165225;
			
			// aapt resource value: 0x7f07000d
			public const int content_frame = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int drawer_layout = 2131165196;
			
			// aapt resource value: 0x7f070013
			public const int duedate = 2131165203;
			
			// aapt resource value: 0x7f07001c
			public const int firmaddress1 = 2131165212;
			
			// aapt resource value: 0x7f07001e
			public const int firmaddress2 = 2131165214;
			
			// aapt resource value: 0x7f070019
			public const int firmname = 2131165209;
			
			// aapt resource value: 0x7f070021
			public const int iban = 2131165217;
			
			// aapt resource value: 0x7f070003
			public const int ibanTxt = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int imageView1 = 2131165193;
			
			// aapt resource value: 0x7f07000e
			public const int left_drawer = 2131165198;
			
			// aapt resource value: 0x7f070007
			public const int linear_layout = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int nameTxt = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int optionsBtn = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int ownerTxt = 2131165188;
			
			// aapt resource value: 0x7f070001
			public const int primary_target = 2131165185;
			
			// aapt resource value: 0x7f070027
			public const int reference = 2131165223;
			
			// aapt resource value: 0x7f070010
			public const int tableLayout1 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int tableRow1 = 2131165201;
			
			// aapt resource value: 0x7f070014
			public const int tableRow2 = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int tableRow3 = 2131165207;
			
			// aapt resource value: 0x7f07001d
			public const int tableRow4 = 2131165213;
			
			// aapt resource value: 0x7f07001a
			public const int tableRow5 = 2131165210;
			
			// aapt resource value: 0x7f07001f
			public const int tableRow6 = 2131165215;
			
			// aapt resource value: 0x7f070022
			public const int tableRow7 = 2131165218;
			
			// aapt resource value: 0x7f070025
			public const int tableRow9 = 2131165221;
			
			// aapt resource value: 0x7f07000a
			public const int text1 = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int text2 = 2131165195;
			
			// aapt resource value: 0x7f070000
			public const int textView1 = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int textView14 = 2131165202;
			
			// aapt resource value: 0x7f070015
			public const int textView15 = 2131165205;
			
			// aapt resource value: 0x7f070018
			public const int textView16 = 2131165208;
			
			// aapt resource value: 0x7f07001b
			public const int textView17 = 2131165211;
			
			// aapt resource value: 0x7f070020
			public const int textView22 = 2131165216;
			
			// aapt resource value: 0x7f070023
			public const int textView29 = 2131165219;
			
			// aapt resource value: 0x7f070026
			public const int textView30 = 2131165222;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int accounts = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int accountview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int appointment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int branches = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int contact = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int credits = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int DrawerListItem = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int List = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ListItem = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int mobilebanking = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int transfers = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int zxingscanneractivitylayout = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int zxingscannerfragmentlayout = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int delete_content_description = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int drawer_close = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int drawer_open = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int dummy_subtitle = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int dummy_title = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int title_section1 = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int title_section2 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int title_section3 = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int touched_primary_message = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int touched_secondary_message = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_ING = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme_ING_ActionBar = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
